/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'},

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
   // Autogenerated sidebar from docs folder structure
    {
      type: 'category',
      label: 'Other Resources', // Static links category
      items: [
        {
          type: 'link',
          label: '🤖 Chat with AI', // Static link label
          href: '/chat', // Static link URL
        },
        {
          type: 'link',
          label: '🚀 Search Lab', // Example external link
          href: 'https://mongodb-developer.github.io/search-lab/', // External link URL
        },
      ],
    }],
};

module.exports = sidebars;
